### ISSUE TITLE
Add the expected values when changing the preform temperature.

### ISSUE THREAD

**Issue by Jerrk** [Toofifty/easy-giantsfoundry#10]
When heating/cooling the preform, the heat seems to be changed with an exponential curve starting of lower and increasing for every game cycle using the pool/waterfall.

I think it would be useful if this formula could be analyzed and then add ticks on the temperature gauge to show how many game cycles until you will reach the desired temperature.

how this would be useful is for example if i just finished using the polishing wheel and my next task is to use the trip hammer, ideally i would want change the temperature to be as far to the right on the red bar as possible. So i would dunk the preform to increase the heat and i would try to gauge the amount of heat i'm gathering per cycle. When i reach close to the end of the red bar depending on how much heat im gathering thanks to the exponential function it's common that i overshoot the red bar and i have to cool off the preform.

If we had ticks on the temperature line to show where the temperature will be in the next few game cycles this would be a nice addition to the plugin.

heres a quick mockup
![](https://i.imgur.com/Y33MTok.png)

In this example i would dunk 7 times in a row, and then restart the dunk and do 2 more and maybe even heat once or twice to reach the maximum temperature for using the trip hammer

**Comment by pwatts6060** [comment]
That's pretty cool idea with the ticks. I have been wanting to do a feature related to knowing about the temperature changes to help not overshooting it. The ticks doesn't require us to make the logic of when you should stop and leaves that to the user which is nice, especially as people have different strategies. I'll look into this.

**Comment by pwatts6060** [comment]
Probably an even better solution has been done now that shows how many dunks/quenches you should do so going to close this now.
