### ISSUE TITLE
Notification threshold

### ISSUE THREAD

**Issue by noahgill409** [Toofifty/easy-giantsfoundry#12]
Please allow the user to configure how many actions in advance a notification is sent. The reason for this is that the outfit pieces add a chance to complete multiple actions, so sometimes the notification comes too late for me.

A good example of this functionality is the one click summer garden plugin (pictured).

![image](https://user-images.githubusercontent.com/14190748/177003230-07be5596-4bd2-4d71-9e6e-6731c6dbe71e.png)

**Comment by noahgill409** [comment]
accidentally clicked the close button

**Comment by Vanillj** [comment]
This should be quite straight forward to implement, might look into it when I get some free time unless someone else do it.
