### ISSUE TITLE
Reputation not tracked on purchase

### ISSUE THREAD

**Issue by Speshkitty** [Toofifty/easy-giantsfoundry#20]
When buying an item from the shop, reputation is not updating correctly.

Issue has been seen with all moulds - I'm yet to buy anything else so I don't know if it's mould specific.

See screenshot
![image](https://user-images.githubusercontent.com/1111285/181924855-069483fc-ede5-4121-97e6-84cef357a220.png)

**Comment by pwatts6060** [comment]
Thanks for the report! We'll get onto that when we can

**Comment by SkrrtNick** [comment]
> Thanks for the report! We'll get onto that when we can

Unsure if you're aware but reward points are held in a config id (I believe that is the RL terminology?) 3436

**Comment by pwatts6060** [comment]
Thanks for the issue request, this will be made available soon in PR https://github.com/Toofifty/easy-giantsfoundry/pull/27.
