### ISSUE TITLE
Suggestion: custom colors for tool status

### ISSUE THREAD

**Issue by ArashiJoe** [Toofifty/easy-giantsfoundry#23]
Something akin to what is seen in other plugins (using Herbiboar as an example):
![image](https://user-images.githubusercontent.com/61663896/186953007-fe33e859-7fd3-4f44-941d-a63eeb3c2ab0.png)

**Comment by pwatts6060** [comment]
Thanks for the issue request, this will be made available soon in PR https://github.com/Toofifty/easy-giantsfoundry/pull/26.
