### ISSUE TITLE
Add support for smithing outfit - increased progress per action makes counts "actions left" count inaccurate

### ISSUE THREAD

**Issue by Drexxil** [Toofifty/easy-giantsfoundry#31]
The full smithing outfit increases the progress gain by the hammer by 5%, the grinding wheel by 10% and the polishing by 10%, 100% of the time.  This makes the "actions left" tab inaccurate when calculating. A Checkbox supporting wearing the full smithing outfit would be helpful for people that play the minigame a lot.

**Comment by HenryBurns** [comment]
+1 here, It'd be a nice QOL feature to have.

**Comment by TalSk** [comment]
Decided to go ahead and add this support. PR #35 
There are no contribution guidelines so not sure what's the rules on CR and merging.

**Comment by pwatts6060** [comment]
@TalSk 's changed have been added so the issue can be closed now.
