### ISSUE TITLE
Add Foundry Reputation count to the EGF window

### ISSUE THREAD

**Issue by Raisoshi** [Toofifty/easy-giantsfoundry#7]
I keep having to open the shop to see how much rep I have, would be nice to have a count at the EGF window that updates after you turn in a sword.

**Comment by pwatts6060** [comment]
I can add this as a toggleable config but unsure if there is a way to grab the foundry reputation value. It doesn't seem to be stored in a varbit. 

It's possible to manually keep track of the reputation by syncing it when you open the shop or buy things. Then when you hand swords in it could add the reputation on. If anyone knows a better way to get the reputation please comment.

**Comment by Vanillj** [comment]
You can grab the widget and use regex to find the points each time you turn in or open the shop. Something like this in ```onGameTick``` in ```EasyGiantsFoundryPlugin``` should work
```java
// global variables 
private boolean increasePoints = false;
@Getter
private int shopPoints;
private static final int SHOPWIDGET = 753;
private static final int CHATWIDGET = 229;
private static final int SHOPPOINTSTEXT = 13;
private static final int CHATPOINTSTEXT = 1;
private static final Pattern pattern = Pattern.compile("quality: (?<points>\\d+) Best");

// in onGameTick
Widget chat = client.getWidget(CHATWIDGET, CHATPOINTSTEXT);

Widget shop = client.getWidget(SHOPWIDGET, SHOPPOINTSTEXT);
if (shop != null && Integer.parseInt(shop.getText()) != shopPoints)
{
	shopPoints = Integer.parseInt(shop.getText());
}

if (chat != null)
{
	String text = Text.sanitizeMultilineText(chat.getText());
	final Matcher m = pattern.matcher(text);
	if (m.find() && increasePoints)
	{
		shopPoints += Integer.parseInt(m.group("points"));
		increasePoints = false;
	}
}
else 
{
	increasePoints = true;
}
```
This is probably not the best code but it's a start.

**Comment by Vanillj** [comment]
It would also be a good idea to always show the overlay (if enabled and you're in the Giants' Foundry) such that when you have handed in and currently is not working on anything it still displays the Title and Points.

**Comment by pwatts6060** [comment]
@Vanillj would you be interested in making a PR for this? I don't have time for this at the moment and want to work on #10 when I get the chance.

**Comment by pwatts6060** [comment]
Added in v1.0.5. I will close this issue once the changes are live.
